version: "3.4"

services:
  frontend:
    build:
      context: .
      target: development
    command: yarn dev
    env_file:
      - .env
      - .env.local
    ports:
      - "3000:3000"
    volumes:
      - .:/react-hooks:delegated

volumes:
  node_modules:
